var classes = [
    {
        "name": "GildedRose",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update_quality",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 20,
        "ccn": 19,
        "ccnMethodMax": 19,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 114,
        "vocabulary": 20,
        "volume": 492.7,
        "difficulty": 25.77,
        "effort": 12698.22,
        "level": 0.04,
        "bugs": 0.16,
        "time": 705,
        "intelligentContent": 19.12,
        "number_operators": 51,
        "number_operands": 63,
        "number_operators_unique": 9,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 57,
        "lloc": 57,
        "mi": 40.29,
        "mIwoC": 40.29,
        "commentWeight": 0,
        "kanDefect": 1.5,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Item",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 8,
        "volume": 57,
        "difficulty": 2.5,
        "effort": 142.5,
        "level": 0.4,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 22.8,
        "number_operators": 4,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.73,
        "mIwoC": 60.73,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "package": "\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]